### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by yashodhank** [humenius/traefik-certs-dumper#5] opened 2020-05-22 11:13 UTC
Thank you so much for building and share it.. :)
Is it possible to set environment DOMAIN: with comma separated list of multiple domains?
Example:
```
# Traefik Certs Dumper - Extract LetsEncrypt Certificates - Traefik2 Compatible
  certdumper:
    container_name: traefik_certdumper
    image: humenius/traefik-certs-dumper:latest
    # command: --restart-containers container1,container2,container3
    volumes:
      - $USERDIR/docker/traefik2/acme:/traefik:ro
      - $USERDIR/docker/shared/certs:/output:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro # only needed if restarting containers
    environment:
      DOMAIN: example.com,example.org,example.net,hello.example.in
```

**Comment by humenius** [comment] 2020-05-24 00:08
Hey, thank you. :)
I think it should be possible. I try to take a look at it on the following days.

**Comment by humenius** [comment] 2020-05-27 07:12
After working on it a little bit, it seems like it might be coming to sort of breaking changes.
I'd suggest to keep the purpose of env var `DOMAIN` to be a single domain and to add a new env var `DOMAINS` being a comma-separated list for the sake of reverse compatibility.
This would also mean, that `DOMAIN` may be deprecated in future releases.

Do you have any other suggestions or is this approach fine?

**Comment by humenius** [comment] 2020-05-27 07:50
I'm currently working on it. But instead of releasing it on its own, I'd like to bundle it with some other changes. But I can provide dev builds which e. g. may include single changes like multiple domains.

**Comment by humenius** [comment] 2020-05-27 09:01
#6 is ready. I tested it and it seems to work. Maybe you want to try it out as well. :)

**Comment by humenius** [comment] 2020-05-27 15:13
Changes have been merged. I'll tag the new version as soon as possible which should then trigger the build of the new image. Enjoy!

**Comment by yashodhank** [comment] 2020-05-29 10:49
It works when I have both domains having their ssl in acme.json

I ran into issue in which traefik2 have not provisioned SSL for one of the domain mentioned in list for traefik-certs-dumper and container exited because it was not able to locate the certificate.

I think container should still keep running, and throw error in log.

Thank you so much..

logs:
```
traefik_certdumper | 2020-05-29T10:41:22.770641836Z [2020-05-29T10:41:22+0000]: --restart-containers is empty. Won't attempt to restart containers.
traefik_certdumper | 2020-05-29T10:41:22.771150349Z [2020-05-29T10:41:22+0000]: Got value of DOMAIN: XXXXXXXce.com,XXXXXud.in. Splitting values.
traefik_certdumper | 2020-05-29T10:41:22.775322114Z [2020-05-29T10:41:22+0000]: Values split! Got 'XXXXXXXce.com XXXXXud.in'
traefik_certdumper | 2020-05-29T10:41:22.775339025Z [2020-05-29T10:41:22+0000]: Clearing dumping directory
traefik_certdumper | 2020-05-29T10:41:22.784159958Z [2020-05-29T10:41:22+0000]: Dumping certificates
traefik_certdumper | 2020-05-29T10:41:22.820754322Z [2020-05-29T10:41:22+0000]: Certificate or key for 'XXXXXXXce.com' differ, updating
traefik_certdumper | 2020-05-29T10:41:22.824012965Z [2020-05-29T10:41:22+0000]: Certificate or key for 'XXXXXud.in' differ, updating
traefik_certdumper | 2020-05-29T10:41:22.825489402Z mv: can't rename '/tmp/work/XXXXXud.in/*.pem': No such file or directory
traefik_certdumper exited with code 1
```

**Comment by humenius** [comment] 2020-05-29 11:29
This is probably caused by `set -e` I left in the script because for some reason, I thought it would be a good idea to fail fast. I'll fix it ASAP.

**Comment by humenius** [comment] 2020-05-30 18:07
Should be fixed now. I added a error message as well. Feel free to test it again. 👍

**Comment by humenius** [comment] 2020-06-03 06:45
I'm sorry that this issue takes a little bit. I try to push the fix today.

**Closed** 2020-06-03 13:41 UTC
Labels: enhancement

**Comment by humenius** [comment] 2020-06-03 13:44
This should the new issue now. Please report if it's working for you again. :)
